### PR TITLE
Fix KL computation for dof != 1

### LINKED ISSUE #238: Negative reported KL divergence for dof>1
I accidentally discovered a strange bug:

```Python
np.random.seed(42)
X = np.random.uniform(-1, 1, size=(1000, 2))
Z = TSNE(verbose=True, dof=100).fit(X)
```

Prints this:
```
--------------------------------------------------------------------------------
TSNE(dof=100, early_exaggeration=12, verbose=True)
--------------------------------------------------------------------------------
===> Finding 90 nearest neighbors using Annoy approximate search using euclidean distance...
   --> Time elapsed: 0.57 seconds
===> Calculating affinity matrix...
   --> Time elapsed: 0.03 seconds
===> Calculating PCA-based initialization...
   --> Time elapsed: 0.00 seconds
===> Running optimization with exaggeration=12.00, lr=83.33 for 250 iterations...
Iteration   50, KL divergence 1.1914, 50 iterations in 0.4213 sec
Iteration  100, KL divergence 1.3487, 50 iterations in 0.3907 sec
Iteration  150, KL divergence 1.3523, 50 iterations in 0.3916 sec
Iteration  200, KL divergence 1.3521, 50 iterations in 0.4010 sec
Iteration  250, KL divergence 1.3525, 50 iterations in 0.3748 sec
   --> Time elapsed: 1.98 seconds
===> Running optimization with exaggeration=1.00, lr=1000.00 for 500 iterations...
Iteration   50, KL divergence -0.8881, 50 iterations in 0.4196 sec
Iteration  100, KL divergence -0.9152, 50 iterations in 0.4037 sec
Iteration  150, KL divergence -0.9160, 50 iterations in 0.4205 sec
Iteration  200, KL divergence -0.9152, 50 iterations in 0.4224 sec
Iteration  250, KL divergence -0.9163, 50 iterations in 0.4239 sec
Iteration  300, KL divergence -0.9164, 50 iterations in 0.4296 sec
Iteration  350, KL divergence -0.9162, 50 iterations in 0.4356 sec
Iteration  400, KL divergence -0.9164, 50 iterations in 0.4249 sec
Iteration  450, KL divergence -0.9168, 50 iterations in 0.4197 sec
Iteration  500, KL divergence -0.9166, 50 iterations in 0.4186 sec
   --> Time elapsed: 4.22 seconds
```

The final embedding looks fine, but the KL divergence is negative. It also happens for some other values of `dof` but not for the default `dof=1`.

### PR DESCRIPTION
**Pull request by dkobak**
This should hopefully fix #238 and in addition implement exact KL computation with arbitrary dof.

### CODE REVIEW

**Comment by dkobak** [comment]
Apologies, this includes changes from #245 because I screwed up my git commits. 

Also, the tests fail with `fatal error: fftw3.h: No such file or directory` and I don't know how this is related to the changes I did.

**Comment by pavlin-policar** [comment]
Wonderful, thanks for tracking down the bug! I guess I forgot to implement the ddof parameter in the positive gradient? So then I suppose the KL divergence was wrong in all the cases up until now? Also, I see two PRs now, and the other one seems to have only one commit. Should I close the other one and accept this one?

**Comment by dkobak** [comment]
Yes, this PR includes both changes -- I wanted to make two separate PRs but screwed something up with my git branches. The other one is not needed anymore.

But what's happening with the tests?

**Comment by dkobak** [comment]
> I guess I forgot to implement the ddof parameter in the positive gradient? So then I suppose the KL divergence was wrong in all the cases up until now? 

Yes. The gradient was implemented correctly, but the KL divergence was computed wrongly, and only gave the right answer for dof=1.

**Comment by pavlin-policar** [comment]
> Yes, this PR includes both changes -- I wanted to make two separate PRs but screwed something up with my git branches. The other one is not needed anymore.

Okay, I guess we can close the other PR then.

I'm looking at the errors now, and I can't really see anything obvious. The `fft.h` error likely isn't really an error but just checks if we can use FFTW, and if not, falls back to numpys FFT implementation. It seems like the culprit is this one here:

> TypeError: expected str, bytes or os.PathLike object, not get_numpy_include

Perhaps there was a recent change in `pip` or some other build tool, and now this trick that I use to dynamically resolve the numpy `include` path doesn't work anymore. It certainly has nothing to do with your change. I'll try to fix it ASAP.

**Comment by pavlin-policar** [comment]
I believe I've fixed this in #249. Could you please rebase this onto the latest master, and then hopefully, everything passes.

**Comment by dkobak** [comment]
Yes but I am traveling now so not sure how soon I'll be able to get to it.
If you can do it yourself, then please go ahead.

**Comment by pavlin-policar** [comment]
Sorry for the delay, setting this up so that I can push to your PR is a pain, but hopefully, the tests pass now.

**Comment by dkobak** [comment]
Great, thanks a lot for taking care of it! And apologies that I could not fix it myself quickly enough. Only back to my computer now.

**Comment by pavlin-policar** [comment]
No worries, thanks for finding the fix!

**Comment by dkobak** [comment]
Could you tag it as 1.0.1 at some point? Would be cool if this bug fix gets into conda.

**Comment by pavlin-policar** [comment]
I'm sorry that this took so long. I've release v1.0.1 with this fix.

**Pull request merged**
